

 CTDM MET PRE-PROCESSOR PROGRAM (METPRO)       VERSION 2.1       LEVEL 871022

          PROGRAM OPTIONS: 

               MODE = 3 IF 0, DO NOT READ NWS SURFACE DATA NOR UPPER AIR DATA,
                              ASSUME CONSTANT SITE CHARACTERISTICS
                        IF 1, DO NOT READ NWS SURFACE DATA NOR UPPER AIR DATA,
                              BUT ASSUME VARIABLE SITE CHARACTERISTICS
                        IF 2, READ NWS SURFACE DATA, BUT NOT UPPER AIR DATA
                        IF 3, READ NWS SURFACE DATA AND UPPER AIR DATA


          LATITUDE (DEG NORTH) =  39.59, LONGITUDE (DEG WEST) =   89.49
          TIME ZONE (HOURS AFTER GMT) =   6.0


          # OF WIND DIRECTION SECTORS FOR SPECIFYING SURFACE CHARACTERISTICS = 4



               WIND DIRECTION SECTORS AND ANGLE RANGES:

               1:  46- 60

               2:  61-120

               3: 121-250

               4: 251- 45



          SECTOR VALUES FOR SURFACE ROUGHNESS (M), ALBEDO, AND BOWEN RATIO:

 VARIABLE  JAN   FEB   MAR   APR   MAY   JUN   JUL   AUG   SEP   OCT   NOV   DEC

 Z0:      .050  .050  .050  .050  .060  .070  .070  .070  .070  .070  .050  .050
 ALBEDO:  .330  .290  .240  .120  .100  .110  .140  .140  .140  .140  .220  .300
 BOWEN:   .550  .550  .300 1.050 1.050 1.050 2.050 2.050  .500  .550  .550  .550
 (SECTOR 1)

 Z0:      .090  .090  .090  .090  .110  .140  .140  .140  .140  .140  .090  .090
 ALBEDO:  .560  .500  .400  .170  .140  .160  .210  .210  .210  .210  .360  .500
 BOWEN:   .910  .910  .460 1.810 1.810 1.810 3.610 3.610  .820  .910  .910  .910
 (SECTOR 2)

 Z0:      .100  .100  .100  .100  .120  .150  .150  .150  .150  .150  .100  .100
 ALBEDO:  .610  .540  .440  .190  .160  .180  .230  .230  .230  .230  .400  .560
 BOWEN:  1.000 1.000  .500 2.000 2.000 2.000 4.000 4.000  .900 1.000 1.000 1.000
 (SECTOR 3)

 Z0:      .090  .090  .090  .090  .110  .140  .140  .140  .140  .140  .090  .090
 ALBEDO:  .560  .500  .400  .170  .140  .160  .210  .210  .210  .210  .360  .500
 BOWEN:   .910  .910  .460 1.810 1.810 1.810 3.610 3.610  .820  .910  .910  .910
 (SECTOR 4)




