CCPCITS
      interface to Subroutine HIDEM[C]
      end
      Subroutine CLSMS
CC
CC---------------------------------------------------------------------
CC--- Author organization- H. E. Cramer Co., Inc.                   ---
CC--- Subroutine code - CLSMS Version 01.1                          ---
CC--- Subroutine description - turn mouse off and transparent.      ---
CC---------------------------------------------------------------------
CC
CC*********************************************************************
CC
      call HIDEM
CC
      return
      end
CCPCITE
