  
 READING INPUT FROM THE MAIN CONTROL FILE

         Run start date:  1/ 1/99    Julian:   1
               end date:  1/ 2/99    Julian:   2

  
 READING DATA FROM THE MET FILE
  
 READING RECEPTOR LOCATIONS FROM THE CONTROL FILE
  
 READING LINK (ETS) DATA FROM THE MAIN INPUT FILE
 
   End of ETS processing subroutine.
 
  
 FINISHED READING CONTROL FILE INPUT
  
 ENTERING MAIN PROCESSING LOOP
   Processing has reached Julian day:  1
  
 END OF PROCESSING LOOP
 
 Preparing output tables and storing them to file.
 
 Program terminated normally
