lf90 COMPLETE.FOR -c -nw -nvm -nwin -o1 -tp -inln -nap -ndal -npca -nsav -nstchk -wo -nchk
lf90 HEADER.FOR   -c -nw -nvm -nwin -o1 -tp -inln -nap -ndal -npca -nsav -nstchk -wo -nchk
lf90 LIBFILE.FOR  -c -nw -nvm -nwin -o1 -tp -inln -nap -ndal -npca -nsav -nstchk -wo -nchk
lf90 LIBPC.FOR    -c -nw -nvm -nwin -o1 -tp -inln -nap -ndal -npca -nsav -nstchk -wo -nchk
lf90 MERGE.FOR    -c -nw -nvm -nwin -o1 -tp -inln -nap -ndal -npca -nsav -nstchk -wo -nchk
lf90 MP2XFOR.FOR  -c -nw -nvm -nwin -o1 -tp -inln -nap -ndal -npca -nsav -nstchk -wo -nchk
lf90 MP3XFOR.FOR  -c -nw -nvm -nwin -o1 -tp -inln -nap -ndal -npca -nsav -nstchk -wo -nchk
lf90 MP4XFOR.FOR  -c -nw -nvm -nwin -o1 -tp -inln -nap -ndal -npca -nsav -nstchk -wo -nchk
lf90 DEPMET1.FOR  -c -nw -nvm -nwin -o1 -tp -inln -nap -ndal -npca -nsav -nstchk -wo -nchk
lf90 DEPMET2.FOR  -c -nw -nvm -nwin -o1 -tp -inln -nap -ndal -npca -nsav -nstchk -wo -nchk
lf90 OSFILE.FOR   -c -nw -nvm -nwin -o1 -tp -inln -nap -ndal -npca -nsav -nstchk -wo -nchk
lf90 OSSETUP.FOR  -c -nw -nvm -nwin -o1 -tp -inln -nap -ndal -npca -nsav -nstchk -wo -nchk
lf90 OSSRPG.FOR   -c -nw -nvm -nwin -o1 -tp -inln -nap -ndal -npca -nsav -nstchk -wo -nchk
lf90 SETUP1.FOR   -c -nw -nvm -nwin -o1 -tp -inln -nap -ndal -npca -nsav -nstchk -wo -nchk
lf90 SETUP2.FOR   -c -nw -nvm -nwin -o1 -tp -inln -nap -ndal -npca -nsav -nstchk -wo -nchk
lf90 SETUPPC.FOR  -c -nw -nvm -nwin -o1 -tp -inln -nap -ndal -npca -nsav -nstchk -wo -nchk
lf90 SFFILE.FOR   -c -nw -nvm -nwin -o1 -tp -inln -nap -ndal -npca -nsav -nstchk -wo -nchk
lf90 STAGE1N2.FOR -c -nw -nvm -nwin -o1 -tp -inln -nap -ndal -npca -nsav -nstchk -wo -nchk
lf90 STAGE3.FOR   -c -nw -nvm -nwin -o1 -tp -inln -nap -ndal -npca -nsav -nstchk -wo -nchk
lf90 UAFILE.FOR   -c -nw -nvm -nwin -o1 -tp -inln -nap -ndal -npca -nsav -nstchk -wo -nchk

lf90 @mprm190.lrf -bind  -nvm -nwin -o1 -tp -inln -nap -ndal -npca -nsav -nstchk -wo -nchk
cfig386 STAGE1N2  -nosignon
lf90 @mprm390.lrf -bind  -nvm -nwin -o1 -tp -inln -nap -ndal -npca -nsav -nstchk -wo -nchk
cfig386 STAGE3    -nosignon
